version: "3.9"
services:

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - .postgres:/var/lib/postgres/data

  web:
    build: .
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - postgres

