# Generated by Django 4.0.4 on 2024-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordstorage',
            old_name='password',
            new_name='_password',
        ),
        migrations.AlterField(
            model_name='passwordstorage',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
