# Generated by Django 4.0.4 on 2024-06-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_rename_password_passwordstorage__password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordstorage',
            old_name='_password',
            new_name='password',
        ),
    ]
